"""Config loader — YAML file + env-var overrides via ${VAR} syntax.

All configuration goes through `Config`. Plugins receive their own slice as
`config["url"]`, `config["api_key"]`, etc. — no global state.
"""
from __future__ import annotations

import os
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

_VAR_RE = re.compile(r"\$\{([A-Z_][A-Z0-9_]*)\}")


def _expand_env(value: Any) -> Any:
    """Recursively expand ${ENV_VAR} references in strings."""
    if isinstance(value, str):
        return _VAR_RE.sub(lambda m: os.environ.get(m.group(1), ""), value)
    if isinstance(value, list):
        return [_expand_env(v) for v in value]
    if isinstance(value, dict):
        return {k: _expand_env(v) for k, v in value.items()}
    return value


@dataclass
class ServerConfig:
    host: str = "0.0.0.0"
    port: int = 9105
    # Cross-origin browser access. Empty (the default) means same-origin only —
    # the bundled PWA is served from this origin, so it needs nothing here.
    # Add explicit origins (e.g. "https://dash.example.com") to let another
    # web app call the API from a browser; "*" opens it to every website.
    cors_origins: list[str] = field(default_factory=list)


@dataclass
class OllamaConfig:
    """Legacy `ollama:` config block. Kept for backwards compatibility —
    prefer `llm:` for new configs (supports OpenAI-compatible backends).
    """
    url: str = "http://localhost:11434"
    small_model: str = "qwen3.5:4b"
    smart_model: str = "qwen3.6:35b-a3b"
    embed_model: str = "nomic-embed-text"
    keep_alive: str = "2m"


@dataclass
class LLMConfig:
    """LLM backend config.

    `backend` is one of: "auto" (default — picks Ollama if url is :11434,
    else OpenAI-compat), "ollama" (native), "openai_compat" (anything that
    speaks /v1/chat/completions — vLLM, LiteLLM, OpenAI, OpenRouter, ...).
    """
    backend: str = "auto"
    url: str = "http://localhost:11434"
    api_key: str = ""
    small_model: str = "qwen3.5:4b"
    smart_model: str = "qwen3.6:35b-a3b"
    embed_model: str = "nomic-embed-text"
    keep_alive: str = "2m"


@dataclass
class AuthConfig:
    """Built-in auth. If `enabled` is false everything is open.

    `api_key` covers programmatic clients (curl, MCP, scripts). `users`
    covers the PWA via session cookie. Either or both can be empty.
    """
    enabled: bool = False
    api_key: str = ""
    users: dict[str, str] = field(default_factory=dict)  # username -> bcrypt hash
    exempt_paths: list[str] = field(default_factory=lambda: [
        "/api/health",
        "/static/",
        "/favicon.ico",
        "/metrics",
        "/openapi.json",
        "/docs",
        "/redoc",
        "/api/auth/login",
    ])
    session_secret: str = ""   # any random string; auto-generated by `init`


@dataclass
class FixerConfig:
    tier1_rules: bool = True
    tier2_small_llm: bool = True
    tier3_smart_llm: bool = True
    backup_dir: str = "./data/backups"
    audit_log: str = "./data/audit_log.md"
    max_files_changed_per_fix: int = 5
    max_lines_changed_per_fix: int = 200
    # Don't re-attempt a fix for the same failure within this window.
    cooldown_seconds: int = 300


@dataclass
class NotifyConfig:
    discord_webhook: str = ""
    generic_webhook: str = ""
    rate_limit_per_hour: int = 20


@dataclass
class AgentConfig:
    enabled: bool = True
    scan_interval: int = 300
    modules: list[str] = field(default_factory=lambda: ["container_doctor", "service_health"])
    fixer: FixerConfig = field(default_factory=FixerConfig)
    notify: NotifyConfig = field(default_factory=NotifyConfig)


@dataclass
class MCPConfig:
    enabled: bool = True
    gated_tools: list[str] = field(default_factory=list)


@dataclass
class SettingsStore:
    store_path: str = "./data/settings.yaml"


@dataclass
class VerifyConfig:
    groups: list[str] = field(default_factory=lambda: ["core", "services", "ai"])
    fix_request_path: str = "./data/fix-request.md"


@dataclass
class Config:
    # Directory for mutable state (agent.db, notifier.json, backups, ...).
    # Relative paths resolve against the process working directory.
    data_dir: str = "./data"
    server: ServerConfig = field(default_factory=ServerConfig)
    ollama: OllamaConfig = field(default_factory=OllamaConfig)  # legacy
    llm: LLMConfig = field(default_factory=LLMConfig)
    auth: AuthConfig = field(default_factory=AuthConfig)
    agent: AgentConfig = field(default_factory=AgentConfig)
    mcp: MCPConfig = field(default_factory=MCPConfig)
    settings: SettingsStore = field(default_factory=SettingsStore)
    verify: VerifyConfig = field(default_factory=VerifyConfig)
    services: dict[str, dict] = field(default_factory=dict)
    # Original parsed dict — preserved so plugins can pick up keys we don't
    # know about at the dataclass level.
    _raw: dict = field(default_factory=dict)

    def service(self, name: str) -> dict | None:
        """Return the raw config block for a named service, or None."""
        return self.services.get(name)

    def data_path(self, *parts: str) -> Path:
        """Resolve a state-file path under the configured data directory."""
        return Path(self.data_dir).joinpath(*parts)


def load_config(path: Path | str = "config.yaml") -> Config:
    path = Path(path)
    if not path.is_file():
        # First-run fallback — return defaults so `homelab-ai run` works
        # even without a config file (no services, agent disabled).
        cfg = Config()
        cfg.agent.enabled = False
        return cfg

    with path.open() as f:
        raw = yaml.safe_load(f) or {}

    raw = _expand_env(raw)

    cfg = Config()
    cfg._raw = raw

    if d := raw.get("data_dir"):
        cfg.data_dir = str(d)
    if s := raw.get("server"):
        cfg.server = ServerConfig(**{k: v for k, v in s.items() if hasattr(ServerConfig, k)})
    if o := raw.get("ollama"):
        cfg.ollama = OllamaConfig(**{k: v for k, v in o.items() if hasattr(OllamaConfig, k)})
    if llm := raw.get("llm"):
        cfg.llm = LLMConfig(**{k: v for k, v in llm.items() if hasattr(LLMConfig, k)})
    if auth := raw.get("auth"):
        users = auth.get("users") or {}
        exempt = auth.get("exempt_paths") or AuthConfig.__dataclass_fields__["exempt_paths"].default_factory()
        cfg.auth = AuthConfig(
            enabled=auth.get("enabled", False),
            api_key=auth.get("api_key", ""),
            users=users,
            exempt_paths=exempt,
            session_secret=auth.get("session_secret", ""),
        )
    if a := raw.get("agent"):
        fixer = FixerConfig(**(a.get("fixer") or {}))
        notify = NotifyConfig(**(a.get("notify") or {}))
        cfg.agent = AgentConfig(
            enabled=a.get("enabled", True),
            scan_interval=a.get("scan_interval", 300),
            modules=a.get("modules") or ["container_doctor", "service_health"],
            fixer=fixer,
            notify=notify,
        )
    if m := raw.get("mcp"):
        cfg.mcp = MCPConfig(**{k: v for k, v in m.items() if hasattr(MCPConfig, k)})
    if v := raw.get("verify"):
        cfg.verify = VerifyConfig(**{k: v for k, v in v.items() if hasattr(VerifyConfig, k)})
    if s := raw.get("settings"):
        cfg.settings = SettingsStore(**{k: v for k, v in s.items() if hasattr(SettingsStore, k)})

    cfg.services = raw.get("services") or {}

    return cfg
