"""First-run wizard: `homelab-ai init`.

Detects an Ollama (or asks for an OpenAI-compatible URL), runs service
discovery, generates an API key, and writes a `config.yaml` next to the
current working directory.

`--yes` runs non-interactively with defaults.
"""
from __future__ import annotations

import asyncio
import os
from pathlib import Path

import yaml

from homelab_ai.auth.passwords import generate_api_key
from homelab_ai.discovery import discover

HEADER = """# Generated by `homelab-ai init`.
# Re-run init at any time to regenerate, or edit by hand.
# Anything you change here survives upgrades.
"""


def _detect_llm_url() -> tuple[str, str]:
    """Return (url, backend) — Ollama at 11434 if reachable, else fall back."""
    import socket
    for host in ("127.0.0.1", "ollama", "host.docker.internal"):
        try:
            with socket.create_connection((host, 11434), timeout=0.5):
                return f"http://{host}:11434", "ollama"
        except OSError:
            continue
    return "http://localhost:11434", "auto"


def _prompt(question: str, default: str) -> str:
    val = input(f"{question} [{default}]: ").strip()
    return val or default


async def _run_discovery(hosts: list[str]) -> list[dict]:
    print(f"Scanning {len(hosts)} host(s) for known services...")
    found = await discover(hosts, timeout_per_probe=1.5, concurrency=20)
    if not found:
        print("  no services detected.")
    else:
        for hit in found:
            note = hit["config"].get("_note", "")
            print(f"  ✓ {hit['plugin']:18} {hit['host']}:{hit['port']}  {note}")
    return found


def _build_config(llm_url: str, llm_backend: str, api_key: str,
                  services: list[dict]) -> dict:
    cfg: dict = {
        "server": {"host": "0.0.0.0", "port": 9105, "cors_origins": []},
        "llm": {
            "backend": llm_backend,
            "url": llm_url,
            "api_key": "",
            "small_model": "qwen3.5:4b",
            "smart_model": "qwen3.6:35b-a3b",
            "embed_model": "nomic-embed-text",
            "keep_alive": "2m",
        },
        "auth": {
            "enabled": True,
            "api_key": api_key,
            "exempt_paths": ["/api/health", "/static/", "/favicon.ico",
                             "/metrics", "/openapi.json", "/docs", "/redoc",
                             "/api/auth/login"],
        },
        "agent": {
            "enabled": True,
            "scan_interval": 300,
            "modules": ["service_health", "disk_watcher", "disk_forecast",
                        "container_doctor", "import_watchdog"],
            "fixer": {
                "tier1_rules": True,
                "tier2_small_llm": True,
                "tier3_smart_llm": False,
                "backup_dir": "./data/backups",
                "audit_log": "./data/audit_log.md",
                "max_files_changed_per_fix": 5,
                "max_lines_changed_per_fix": 200,
            },
            "notify": {"discord_webhook": "", "rate_limit_per_hour": 20},
        },
        "services": {hit["plugin"]: {k: v for k, v in hit["config"].items()
                                     if not k.startswith("_")}
                     for hit in services},
    }
    return cfg


def run_init(config_path: Path, yes: bool = False) -> int:
    print("=== homelab-ai init ===\n")
    if config_path.exists() and not yes:
        ans = input(f"{config_path} already exists. Overwrite? [y/N]: ").strip().lower()
        if ans != "y":
            print("aborted.")
            return 1

    llm_url, llm_backend = _detect_llm_url()
    if yes:
        print(f"LLM: {llm_backend} at {llm_url}")
    else:
        llm_url = _prompt("LLM backend URL", llm_url)
        llm_backend = _prompt("LLM backend (ollama|openai_compat|auto)", llm_backend)

    api_key = generate_api_key()
    print(f"\nGenerated API key: {api_key}")
    print("(save this — it will be in config.yaml)\n")

    # Probe localhost. Users in Docker compose can edit and add hosts.
    hosts = ["127.0.0.1"]
    if extra := os.environ.get("HOMELAB_AI_DISCOVERY_HOSTS"):
        hosts.extend([h.strip() for h in extra.split(",") if h.strip()])

    discovered = asyncio.run(_run_discovery(hosts))

    cfg = _build_config(llm_url, llm_backend, api_key, discovered)

    config_path.parent.mkdir(parents=True, exist_ok=True)
    with config_path.open("w") as f:
        f.write(HEADER)
        yaml.safe_dump(cfg, f, sort_keys=False, default_flow_style=False)

    print(f"\nWrote {config_path}")
    print("\nNext:")
    print(f"  homelab-ai --config {config_path} run")
    print(f"  curl -H 'X-Api-Key: {api_key}' http://localhost:{cfg['server']['port']}/api/health")
    return 0
